In [1]:
#Numpy

In [2]:
import numpy as np

In [3]:
#criando uma matriz unidimensional
matriz = np.array([1,2,3,4,5])
print(matriz)
print(type(matriz))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#criando matriz com elementos do tipo float e do tipo int
matrizfloat = np.array([1.2, 13.5, 76.8, 3, 5.9], dtype = np.float64)
print(matrizfloat)
print(type(matrizfloat))
matrizint = np.array([1.2, 13.5, 76.8, 3, 5.9], dtype = np.int32)
print(matrizint)
print(type(matrizint))

[ 1.2 13.5 76.8  3.   5.9]
<class 'numpy.ndarray'>
[ 1 13 76  3  5]
<class 'numpy.ndarray'>


In [6]:
#mudando o tipo dos elementos da matriz
matriz1 = np.array([1.2, 13.5, 76.8, 3, 5.9])
print(matriz1)

matriz1int = matriz1.astype(np.int32)
print(matriz1int)

[ 1.2 13.5 76.8  3.   5.9]
[ 1 13 76  3  5]


In [8]:
#criando uma matriz bidimensional
matriz2 = np.array([[34,56,2], [54,7,90], [1,34,645]])
print(matriz2)

[[ 34  56   2]
 [ 54   7  90]
 [  1  34 645]]


In [10]:
#criando arrays vazias tipificadas (vazio = que não são inicializados)
vazio = np.empty([3,2], dtype = int)
print(vazio)

[[0 0]
 [0 0]
 [0 0]]


In [11]:
#criando matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#criando matriz 4x3 com valores iguais a 1
um = np.ones([4,3])
print(um)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#criando matriz identidade
identidade = np.eye(5)
print(identidade)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#criando valores aleatórios entre zero e um
aleatorio = np.random.random(5)
print(aleatorio)

[0.61383408 0.64567001 0.22528196 0.85451874 0.17893738]


In [16]:
#criando valores aleatorios de distribuição normal
aleatorio2 = np.random.randn(5)
print(aleatorio2)

[-1.97086095e-01 -2.77926347e+00  6.41551929e-01 -4.71050722e-04
 -3.21045445e-01]


In [18]:
#criando matriz 3x4 com valores aleatorios
aleatorio3 = np.random.random((3,4))
print(aleatorio3)

[[0.608304   0.25864933 0.60577437 0.43850622]
 [0.20916861 0.96674579 0.03535855 0.737013  ]
 [0.99126639 0.90889382 0.92367253 0.23419381]]


In [25]:
#removendo repetições de um conjunto de dados
rep = np.array([1,2,2,3,4,5,5,5,5,6,7,8,8,9,45])
rep = np.unique(rep)
print(rep)

[ 1  2  3  4  5  6  7  8  9 45]


In [27]:
#mostrando elemento específico de uma matriz
print(matriz2)
print(matriz2[0][1])

[[ 34  56   2]
 [ 54   7  90]
 [  1  34 645]]
56


In [28]:
#mostrando o tamanho da dimensão da matriz
print(matriz2.shape)

(3, 3)


In [36]:
#usando algumas funções matemáticas
print(matriz2)
print("-------------")
#mostrando o maior valor da matriz
print(matriz2.max())
#mostrando o menor valor da matriz
print(matriz2.min())
#mostrando a soma dos valores da matriz
print(matriz2.sum())
#mostrando a média dos valores da matriz
print(matriz2.mean())
#mostrando o desvio padrão da matriz
print(matriz2.std())
#mostrando o valor da raiz quadrada de todos os elementos
print(np.sqrt(matriz2))
#mostrando o valor do exponencial de todos os elementos
print(np.exp(matriz2))

[[ 34  56   2]
 [ 54   7  90]
 [  1  34 645]]
645
1
923
102.55555555555556
193.7593645685924
[[ 5.83095189  7.48331477  1.41421356]
 [ 7.34846923  2.64575131  9.48683298]
 [ 1.          5.83095189 25.3968502 ]]
[[5.83461743e+014 2.09165950e+024 7.38905610e+000]
 [2.83075330e+023 1.09663316e+003 1.22040329e+039]
 [2.71828183e+000 5.83461743e+014 1.31807714e+280]]


In [45]:
#extraindo elementos de uma matriz
print(matriz)
print("----------------")
#mostrando o elemento da posição 2
print(matriz[1])
#mostrando o array criado a partir da primeira posição até 2
print(matriz[0:2])
#mostrando o array criado a partir da primeira posição até o final
print(matriz[0:])
#mostrando o array criado a partir da penúltima posição até o final
print(matriz[-2:])

[1 2 3 4 5]
----------------
2
[1 2]
[1 2 3 4 5]
[4 5]


In [50]:
#extraindo linhas e colunas de uma matriz
print(matriz2)
print("-------------")
#extraindo primeira linha
l1 = matriz2[0,:]
print(l1)
#extraindo segunda coluna
c2 = matriz2[:,1]
print(c2)

[[ 34  56   2]
 [ 54   7  90]
 [  1  34 645]]
-------------
[34 56  2]
[56  7 34]


In [59]:
#calculando as operações de adição e multiplicação de matrizes
m1 = np.array([[23,4], [3,4]])
m2 = np.array([[3,45], [32,9]])
print(m1)
print(m2)
print("-------------")
#somando
soma = m1 + m2
print(soma)
#multiplicando
mult = m1*m2
print(mult)

[[23  4]
 [ 3  4]]
[[ 3 45]
 [32  9]]
-------------
[[26 49]
 [35 13]]
[[ 69 180]
 [ 96  36]]


In [60]:
#transpondo uma matriz
print(matriz2)
print("-------------")
transposta = matriz2.T
print(transposta)

[[ 34  56   2]
 [ 54   7  90]
 [  1  34 645]]
-------------
[[ 34  54   1]
 [ 56   7  34]
 [  2  90 645]]


In [64]:
#usando função where
#criando matriz com números aleatórios positivos e negativos
x = np.random.randn(3,4)
print(x)
print("-------------")
#identificando os positivos e negativos
y = (x > 0)
print(y)
print("-------------")
#usando função where para criar matriz com valores 1 e -1
z = np.where(y>0, 1, -1)
print(z)

[[-0.23667061 -0.88214523 -0.26842276  1.32167413]
 [-1.43798149 -1.73956555  0.13758465  0.80507052]
 [ 0.9546119  -1.15545593 -0.00800077  0.06732188]]
-------------
[[False False False  True]
 [False False  True  True]
 [ True False False  True]]
-------------
[[-1 -1 -1  1]
 [-1 -1  1  1]
 [ 1 -1 -1  1]]
